-- AlterTable
ALTER TABLE `Game` ADD COLUMN `maxPlayers` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `minPlayers` INTEGER NOT NULL DEFAULT 2,
    ADD COLUMN `playTime` INTEGER NOT NULL DEFAULT 0,
    MODIFY `type` VARCHAR(191) NOT NULL DEFAULT 'Board Game';
